### ISSUE TITLE
运行报错：AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by bihaichaosheng1** [oGsLP/kuaishou-crawler#20]
Traceback (most recent call last):
  File "C:/mypythonfile/car_info/driving_attention_video/kuaishou-crawler/ks.py", line 28, in <module>
    crawl()
  File "C:/mypythonfile/car_info/driving_attention_video/kuaishou-crawler/ks.py", line 22, in crawl
    crawler.crawl()
  File "C:\mypythonfile\car_info\driving_attention_video\kuaishou-crawler\lib\crawler.py", line 81, in crawl
    self.__crawl_user(uid)
  File "C:\mypythonfile\car_info\driving_attention_video\kuaishou-crawler\lib\crawler.py", line 122, in __crawl_user
    self.__crawl_work(dir, works[j], j + 1)
  File "C:\mypythonfile\car_info\driving_attention_video\kuaishou-crawler\lib\crawler.py", line 178, in __crawl_work
    v_url = re.search(pattern, html).group(1)+".mp4"
AttributeError: 'NoneType' object has no attribute 'group'

第一次可以运行，但是下载了十几个视频之后就一直报错

**Comment by legolas-zeng** [comment]
你把请求的html打印出来看看，是不是提示要验证码，这个问题明显是被快手检测到了。

**Comment by ccoQQQ** [comment]
出现这个问题后  手机分享出来的链接 就点不动了 无法操作
