### ISSUE TITLE
爬取出错

### ISSUE THREAD

**Issue by xintonglaile** [oGsLP/kuaishou-crawler#22]
Traceback (most recent call last):
  File "ks.py", line 28, in <module>
  File "ks.py", line 22, in crawl
  File "lib\crawler.py", line 73, in crawl
  File "lib\crawler.py", line 113, in __crawl_user
  File "lib\crawler.py", line 167, in __crawl_work
AttributeError: 'NoneType' object has no attribute 'group'
[932] Failed to execute script ks

**Comment by alienxy** [comment]
我也遇到这个问题，请问你解决了吗?
