### ISSUE TITLE
exe执行总是报错

### ISSUE THREAD

**Issue by alienxy** [oGsLP/kuaishou-crawler#30]
报错如下，隔几天运行时，一开始可以正常下载，大概下载几十个之后就会报错，然后再次运行一直都是这个报错，需要隔几天后再次运行，如此反复。
Traceback (most recent call last):
  File "ks.py", line 28, in <module>
  File "ks.py", line 22, in crawl
  File "lib\crawler.py", line 73, in crawl
  File "lib\crawler.py", line 113, in __crawl_user
  File "lib\crawler.py", line 167, in __crawl_work
AttributeError: 'NoneType' object has no attribute 'group'
[19088] Failed to execute script ks

**Comment by smalloneperson** [comment]
也是一样的报错，有解决方案吗？
